/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pithautsob;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MH Habib
 */
public class Insert extends javax.swing.JFrame {

    /**
     * Creates new form Insert
     */
    Connection conn=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    public Insert() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pithaName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        insertBTN = new javax.swing.JButton();
        mainFrame = new javax.swing.JButton();
        updateBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        serial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setName("insert"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteBTN.setBackground(new java.awt.Color(153, 0, 0));
        deleteBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(255, 255, 0));
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        deleteBTN.setText("Delete Pitha");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Pitha's Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 30));

        pithaName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pithaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Pitha Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, 30));

        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 170, 30));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMIN PITHA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cake (2).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 80, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Bread (2)_1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 90, 90));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 90));

        insertBTN.setBackground(new java.awt.Color(0, 102, 51));
        insertBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        insertBTN.setForeground(new java.awt.Color(255, 255, 0));
        insertBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        insertBTN.setText("Insert Pitha");
        insertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBTNActionPerformed(evt);
            }
        });
        getContentPane().add(insertBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, 30));

        mainFrame.setBackground(new java.awt.Color(153, 51, 0));
        mainFrame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mainFrame.setForeground(new java.awt.Color(255, 255, 0));
        mainFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/house.png"))); // NOI18N
        mainFrame.setText("Home");
        mainFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrameActionPerformed(evt);
            }
        });
        getContentPane().add(mainFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 30));

        updateBTN.setBackground(new java.awt.Color(0, 153, 153));
        updateBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(255, 255, 0));
        updateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        updateBTN.setText("Update Pitha");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        getContentPane().add(updateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, 30));

        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Pitha Name", "Price"
            }
        ));
        adminTable.setToolTipText("");
        adminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 350, 290));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 190, 170, -1));

        serial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        serial.setText("Keep empty");
        getContentPane().add(serial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Serial No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 30));

        setSize(new java.awt.Dimension(663, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
         try{
            String sql="DELETE FROM pithavalue WHERE serial=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,serial.getText());
            ps.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Data deleted Successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
         showTableData();
         serial.setText("");
         pithaName.setText("");
         price.setText("");
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void insertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBTNActionPerformed
        // TODO add your handling code here:
        try{
            String sql="INSERT INTO pithavalue"
                    +"(PithaName, price) "
                    +"VALUES (?,?)";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,pithaName.getText());
            ps.setString(2,price.getText());
            ps.executeUpdate();
           // JOptionPane.showMessageDialog(null, "Data Inserted Successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        showTableData();
        serial.setText("");
        pithaName.setText("");
        price.setText("");
    }//GEN-LAST:event_insertBTNActionPerformed

    private void mainFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFrameActionPerformed
        // TODO add your handling code here:
        new NewJFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_mainFrameActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE pithavalue SET pithaname=?,price=? WHERE serial=?";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            ps=conn.prepareStatement(sql);
            ps.setString(1,pithaName.getText());
            ps.setString(2,price.getText());
            ps.setString(3,serial.getText());
            ps.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Data updated Successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        showTableData();
        serial.setText("");
        pithaName.setText("");
        price.setText("");
    }//GEN-LAST:event_updateBTNActionPerformed

    private void adminTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTableMouseClicked
        // TODO add your handling code here:
        int i=adminTable.getSelectedRow();
        TableModel model=adminTable.getModel();
        serial.setText(model.getValueAt(i, 0).toString());
        pithaName.setText(model.getValueAt(i, 1).toString());
        price.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_adminTableMouseClicked
    public void showTableData(){
        try{
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            String sql="SELECT *FROM pithavalue";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            adminTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminTable;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton insertBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainFrame;
    private javax.swing.JTextField pithaName;
    private javax.swing.JTextField price;
    private javax.swing.JTextField serial;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
