/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pithautsob; 

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.JRConstants;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author MH Habib
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
 
    Connection conn=null;
    PreparedStatement ps=null;
    PreparedStatement pt=null;
    ResultSet rs=null;
    ResultSet rt=null;
    Connection CONEX;
    public NewJFrame() {
        initComponents();
        showTableData();
        showYear();
    }
    public void showYear()
    {
        int year;
        String yes;
        GregorianCalendar gcalendar = new GregorianCalendar();
        year = gcalendar.get(Calendar.YEAR);
        
        lyear.setText(Integer.toString(year));

        
    }
    public void showTableData(){
        try{
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            String sql="SELECT *FROM pithavalue";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();
            pithalist.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lyear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pithalist = new javax.swing.JTable();
        pithaName = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTable();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        print = new javax.swing.JButton();
        total = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CostTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lyear.setFont(new java.awt.Font("DAGGERSQUARE", 1, 72)); // NOI18N
        lyear.setForeground(new java.awt.Color(102, 0, 51));
        getContentPane().add(lyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 180, 70));

        pithalist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial", "Pitha Name", "Price"
            }
        ));
        pithalist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pithalistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pithalist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 320, 310));

        pithaName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(pithaName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 180, 30));

        Price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 180, 30));

        quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 170, 30));

        receipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PITHA NAME", "PRICE", "QUANTITY", "TOTAL"
            }
        ));
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(receipt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 380, 270));

        submit.setBackground(new java.awt.Color(0, 102, 102));
        submit.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tick-inside-circle.png"))); // NOI18N
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 360, 130, 30));

        reset.setBackground(new java.awt.Color(153, 0, 0));
        reset.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update.png"))); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 110, 30));

        print.setBackground(new java.awt.Color(153, 51, 0));
        print.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer (2).png"))); // NOI18N
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 130, 30));

        total.setBackground(new java.awt.Color(0, 102, 51));
        total.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        total.setText("TOTAL");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 110, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Pitha Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 130, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Pitha Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Pitha Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 130, 30));

        jLabel4.setFont(new java.awt.Font("DAGGERSQUARE", 1, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 51));
        jLabel4.setText("PITHA FESTIVAL - ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 620, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/piece-of-cake (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 90, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pie (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, 80, 70));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("DEPARTMENT OF COMPUTER SCIENCE & ENINGINEERING, JUST");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 740, 30));

        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 4, true));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 120));

        CostTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CostTotal.setForeground(new java.awt.Color(102, 0, 51));
        CostTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(CostTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 160, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Total amount to be paid");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 220, 30));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 0));

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        jMenuItem1.setText("Admin Panel");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Developer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1122, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) receipt.getModel();
        int i = Integer.parseInt(Price.getText());
        int j= Integer.parseInt(quantity.getText());
        int ans=i*j;
        model.addRow(new Object[]{pithaName.getText(),Price.getText(),quantity.getText(),ans});
        try{
            String sql="INSERT INTO totalprice"
                    +"(PithaName, Price,Quantity,Total) "
                    +"VALUES ('"+pithaName.getText()+"','"+Price.getText()+"','"+quantity.getText()+"',Price*Quantity)";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            ps.executeUpdate(sql);
           // JOptionPane.showMessageDialog(null, "Data Inserted Successfully!");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        pithaName.setText("");
        Price.setText("");
        quantity.setText("");
    }//GEN-LAST:event_submitActionPerformed

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptMouseClicked

    private void pithalistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pithalistMouseClicked
        // TODO add your handling code here:
        int i=pithalist.getSelectedRow();
        TableModel model=pithalist.getModel();
        pithaName.setText(model.getValueAt(i, 1).toString());
        Price.setText(model.getValueAt(i, 2).toString());
    }//GEN-LAST:event_pithalistMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel)receipt.getModel();
        while(dm.getRowCount() > 0)
        {
            dm.removeRow(0);
        }
        try{
            String sql="DELETE FROM `totalprice`";
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            ps.executeUpdate(sql);
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        CostTotal.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed

        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/pitha","root","");
            String rp="H:\\PithaUtsob\\src\\pithautsob\\Vreport.jrxml";
            JasperReport jr=JasperCompileManager.compileReport(rp);
            JasperPrint jp=JasperFillManager.fillReport(jr,null,conn);
            JasperViewer.viewReport(jp);
            conn.close();
            
            
        }catch(Exception ex)
        {
             System.out.println(ex.getMessage());
         }
    }//GEN-LAST:event_printActionPerformed
    
    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        
         try{
            String sql="SELECT SUM(Total) FROM totalprice";
            String sqll="SELECT * FROM totalprice";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();  
            pt=conn.prepareStatement(sqll);
            rt=pt.executeQuery();  
            receipt.setModel(DbUtils.resultSetToTableModel(rt));
            while(rs.next())
            {
               String fn = rs.getString("SUM(Total)");
                CostTotal.setText(fn);
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_totalActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        new Insert().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new Insert().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new profile().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CostTotal;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lyear;
    private javax.swing.JTextField pithaName;
    private javax.swing.JTable pithalist;
    private javax.swing.JButton print;
    private javax.swing.JTextField quantity;
    private javax.swing.JTable receipt;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables

}
